#!/usr/bin/python3
import pygame, sys

# Constants
SCREEN_WIDTH = 576
SCREEN_HEIGHT = 1024


# Main pygame function and variables
pygame.init()
screen = pygame.display.set_mode((SCREEN_WIDTH,SCREEN_HEIGHT))
clock = pygame.time.Clock()

# Main game magic
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
        if event.type == pygame.K_SPACE:
            print('Space is pressed')
            # Todo action on jump

    pygame.display.update()
    clock.tick(120)
